### ISSUE TITLE
Vulcanize >= v1.9.0 support

### ISSUE THREAD

**Issue by dunnkers** [mbykovskyy/broccoli-vulcanize#10]
This broccoli plugin is currently broken when combined with Polymer because of a breaking API change back in Vulcanize v1.9.0 and no vulcanize backwards compatibility in regards to the recent Polymer releases. Therefore the plugin has to be slightly rewritten.

Is anyone already on this? - if no, I am willing to fix this issue.

**Comment by mbykovskyy** [comment]
Unfortunately I haven't been working with Polymer lately so I haven't had time to maintain this plugin. You're more than welcome to contribute!

**Comment by mbykovskyy** [comment]
This should be fixed in `v.3.0.0`. I bumped `vulcanize` version to `1.14.8`.

**Comment by dunnkers** [comment]
Great work @mbykovskyy!
