### ISSUE TITLE
Update vulcanize

### ISSUE THREAD

**Issue by jordpo** [mbykovskyy/broccoli-vulcanize#3]
Any plans to update the vulcanize version? there is an issue with earlier versions and the current version of Polymer:

http://stackoverflow.com/questions/27769385/vulcanization-breaks-polymer-code-uncaught-typeerror-undefined-is-not-a-functi

**Comment by mbykovskyy** [comment]
Done, version `1.0.5` is released.

**Comment by jordpo** [comment]
awesome - thanks!
