### ISSUE TITLE
CSS Import problem

### ISSUE THREAD

**Issue by matheusdavidson** [mbykovskyy/broccoli-vulcanize#4]
Im using this addon with ember and now with polymer 0.8 they using some css import like this:
``<link rel="import" type="css" href="paper-checkbox.css">``

This insert the css without ``<style>`` tag making components go crazy!

Is there any way i can fix this? thank you.

https://github.com/Polymer/vulcanize/pull/152

**Comment by mbykovskyy** [comment]
It looks like there needs to be a bit of work. I tried upgrading to the latest `vulcanize` version to get the fix but unfortunately they changed the interface at some stage.

**Comment by mbykovskyy** [comment]
@matheusdavidson It looks like the latest `vulcanize` version doesn't included the fix yet. I upgraded `vulcanize` to the latest version anyway so at least now HTML won't include CSS content. It required some interface changes which means some options that you've been specifying might have changed. You should check [vulcanize options](https://github.com/Polymer/vulcanize#options) to see if yours are different.

When they include the fix in their release I'll upgrade `vulcanize` again or send me a pull request as I work on something else at the moment and don't track changes to `polymer` or `vulcanize`.

**Comment by mbykovskyy** [comment]
@matheusdavidson Should be fixed in `2.0.2`.

**Comment by matheusdavidson** [comment]
Thank you, im upgrading :smile:
